app :
  name : "LiyeNortors"
pg :
  host : "localhost"
  user : "postgres"
  dbname : "melina"
  password : "061202xixi"
  port : "5432"
redis :
  host : "localhost"
  port : "6379"
  password : ""
smtp :
  email : ""
  password : ""
file :
  savepath : ""
grpc :
  host : ""
  port : ""
